# Generated by Django 5.2 on 2025-07-19 06:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_clothing_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='clothing',
            old_name='id',
            new_name='product_id',
        ),
        migrations.AddField(
            model_name='clothing',
            name='brand',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clothing',
            name='category',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clothing',
            name='gender',
            field=models.CharField(default=None, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clothing',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clothing',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clothing',
            name='size',
            field=models.TextField(default=None, max_length=7),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='review',
            fields=[
                ('review_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description_review', models.TextField(max_length=80)),
                ('stars', models.IntegerField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('product_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.clothing')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
