# Generated by Django 5.2.4 on 2025-07-27 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_clothing_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothing',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2),
            preserve_default=False,
        ),
    ]
