# Generated by Django 5.2 on 2025-07-19 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_id_clothing_product_id_clothing_brand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothing',
            name='brand',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='clothing',
            name='category',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='clothing',
            name='desc',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='clothing',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
