# Generated by Django 5.2 on 2025-08-03 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_orderitem_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='variant_id',
            field=models.ForeignKey(default='e397d4916f1945c082b9809762f089ad', on_delete=django.db.models.deletion.PROTECT, to='base.productvariant'),
            preserve_default=False,
        ),
    ]
