# Generated by Django 5.2.4 on 2025-07-27 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_clothing_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothing',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
