# Generated by Django 5.2.4 on 2025-07-27 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_clothing_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothing',
            name='details',
            field=models.TextField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
