# Generated by Django 5.2 on 2025-07-19 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_clothing_brand_alter_clothing_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothing',
            name='desc',
            field=models.TextField(max_length=1000),
        ),
    ]
