# Generated by Django 5.2 on 2025-08-03 15:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_orderitem_variant_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothing',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clothing',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
