# Generated by Django 5.2 on 2025-08-04 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_clothing_created_clothing_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='color',
            field=models.CharField(default='Black', max_length=50),
            preserve_default=False,
        ),
    ]
