# Generated by Django 5.2 on 2025-07-19 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_clothing_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothing',
            name='rating',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
        migrations.AlterField(
            model_name='clothing',
            name='size',
            field=models.TextField(max_length=40),
        ),
    ]
