# Generated by Django 5.2.4 on 2025-07-27 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_clothing_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='paid_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
