# Generated by Django 5.2 on 2025-07-31 14:10

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_order_paid_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clothing',
            name='stock',
        ),
        migrations.AlterField(
            model_name='review',
            name='stars',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='review',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ClothingColour',
            fields=[
                ('colour_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('colour', models.CharField()),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.clothing')),
            ],
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('variant_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('size', models.CharField(max_length=10)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('colour_variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sizes', to='base.clothingcolour')),
            ],
        ),
    ]
