# Generated by Django 5.2 on 2025-07-19 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_clothing_rating_alter_clothing_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothing',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
