# Generated by Django 5.2 on 2025-08-04 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_productvariant_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='color',
        ),
    ]
