# Generated by Django 5.2 on 2025-07-20 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_clothing_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clothing',
            old_name='desc',
            new_name='description',
        ),
    ]
