# Generated by Django 5.2 on 2025-07-31 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_remove_clothing_stock_alter_review_stars_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClothingColour',
            new_name='ClothingColor',
        ),
        migrations.RenameField(
            model_name='clothingcolor',
            old_name='colour',
            new_name='color',
        ),
        migrations.RenameField(
            model_name='clothingcolor',
            old_name='colour_id',
            new_name='color_id',
        ),
        migrations.RenameField(
            model_name='productvariant',
            old_name='colour_variant',
            new_name='color_variant',
        ),
        migrations.RemoveField(
            model_name='clothing',
            name='created',
        ),
        migrations.RemoveField(
            model_name='clothing',
            name='updated',
        ),
    ]
