# Generated by Django 5.2 on 2025-08-04 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_remove_productvariant_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productvariant',
            old_name='color_variant',
            new_name='color',
        ),
    ]
