# Generated by Django 5.2 on 2025-07-31 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_rename_clothingcolour_clothingcolor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothingcolor',
            name='color',
            field=models.CharField(blank=True, null=True),
        ),
    ]
