# Generated by Django 5.2 on 2025-07-20 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_rename_desc_clothing_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothing',
            name='category',
            field=models.CharField(max_length=20),
        ),
    ]
