# Generated by Django 5.2 on 2025-07-31 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_clothingcolor_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='product_id',
            field=models.ForeignKey(default='59c559f537fd489daae1453cecd9d335', on_delete=django.db.models.deletion.PROTECT, to='base.clothing'),
            preserve_default=False,
        ),
    ]
