# Generated by Django 5.2 on 2025-07-24 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_clothing_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothing',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='clothing',
            name='updated',
            field=models.DateField(auto_now=True),
        ),
    ]
