# Generated by Django 5.2 on 2025-07-26 05:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_clothing_created_alter_clothing_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='description_review',
            field=models.TextField(max_length=600),
        ),
        migrations.AlterField(
            model_name='review',
            name='stars',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(5)]),
        ),
    ]
