# Generated by Django 5.2 on 2025-07-26 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_review_description_review_alter_review_stars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='description_review',
            field=models.TextField(max_length=1000),
        ),
    ]
